import { GroceryItem, RecipeCard } from "@/lib/types";

export const recentDinnerHistory = [
  "Paneer tikka wraps",
  "Moong chilla with curd",
  "Palak paneer with phulka",
  "Masala oats khichdi",
];

export const recipeLibrary: RecipeCard[] = [
  {
    id: "masala-paneer-bowls",
    name: "Masala Paneer Millet Bowls",
    cuisine: "Gujarati comfort",
    prepMinutes: 30,
    proteinGrams: 31,
    spiceProfile: "Warm masala, mint curd, fresh coriander",
    whyItWorks: "High protein, familiar flavors, and fast enough for a weekday dinner.",
    ingredients: [
      "Paneer cubes",
      "Cooked millet or rice",
      "Capsicum",
      "Onion",
      "Tomato",
      "Mint curd drizzle",
      "Roasted peanuts",
    ],
    method: [
      "Cook onion, capsicum, and tomato with cumin, turmeric, and coriander powder.",
      "Fold in paneer and cook only until warm so it stays soft.",
      "Serve over millet or rice with mint curd and roasted peanuts.",
    ],
    tags: ["high protein", "weekday", "veg"],
  },
  {
    id: "rajma-tostada-chaat",
    name: "Rajma Tostada Chaat",
    cuisine: "Global snacky dinner",
    prepMinutes: 28,
    proteinGrams: 24,
    spiceProfile: "Tangy chaat masala and smoky rajma",
    whyItWorks: "Feels fresh without needing unusual ingredients.",
    ingredients: [
      "Cooked rajma",
      "Crisp tostadas or toasted rotis",
      "Hung curd",
      "Onion",
      "Tomato",
      "Lettuce or cabbage",
      "Chaat masala",
    ],
    method: [
      "Warm rajma with tomato, cumin, garlic, and Kashmiri chili.",
      "Spread hung curd over tostadas or crisp rotis.",
      "Top with rajma, vegetables, and chaat masala.",
    ],
    tags: ["fun dinner", "protein", "crispy"],
  },
  {
    id: "tofu-makhani-noodles",
    name: "Tofu Makhani Noodles",
    cuisine: "Fusion comfort",
    prepMinutes: 25,
    proteinGrams: 27,
    spiceProfile: "Creamy tomato makhani with ginger and kasuri methi",
    whyItWorks: "Brings variety while keeping flavors familiar.",
    ingredients: [
      "Firm tofu",
      "Whole wheat noodles",
      "Tomato puree",
      "Cashew paste",
      "Ginger",
      "Kasuri methi",
      "Peas",
    ],
    method: [
      "Sear tofu until lightly golden.",
      "Cook a quick makhani base with tomato, ginger, cashew paste, and spices.",
      "Fold in noodles, peas, and tofu until glossy.",
    ],
    tags: ["world food", "comfort", "veg"],
  },
  {
    id: "besan-spinach-cheela-tacos",
    name: "Besan Spinach Cheela Tacos",
    cuisine: "Indian handheld dinner",
    prepMinutes: 24,
    proteinGrams: 22,
    spiceProfile: "Fresh, green, and lightly spicy",
    whyItWorks: "Fast, budget-friendly, and easy on lighter training days.",
    ingredients: [
      "Besan batter",
      "Spinach",
      "Paneer crumble",
      "Cabbage slaw",
      "Mint curd",
      "Roasted sesame",
    ],
    method: [
      "Make thin spinach cheelas.",
      "Fill with paneer crumble, slaw, and mint curd.",
      "Finish with sesame and lemon.",
    ],
    tags: ["quick", "budget", "veg"],
  },
  {
    id: "palak-chana-bake",
    name: "Palak Chana Cottage Bake",
    cuisine: "Protein-first family dinner",
    prepMinutes: 35,
    proteinGrams: 29,
    spiceProfile: "Palak, tomato, warm garam masala",
    whyItWorks: "Comforting enough for the whole house while still helping post-workout recovery.",
    ingredients: [
      "Boiled chana",
      "Spinach puree",
      "Paneer",
      "Onion",
      "Tomato",
      "Garlic",
      "Light cheese",
    ],
    method: [
      "Make a spinach-tomato masala base.",
      "Fold in chana and paneer.",
      "Top lightly with cheese and bake until bubbling.",
    ],
    tags: ["post workout", "shared dinner", "comfort"],
  },
];

export const baseGroceries: GroceryItem[] = [
  { id: "curd", label: "Curd / yogurt", quantity: "1 tub", aisle: "Dairy", checked: false },
  { id: "paneer", label: "Paneer", quantity: "500 g", aisle: "Dairy", checked: false },
  { id: "coriander", label: "Fresh coriander", quantity: "2 bunches", aisle: "Produce", checked: false },
  { id: "lemon", label: "Lemon", quantity: "6", aisle: "Produce", checked: false },
  { id: "capsicum", label: "Capsicum", quantity: "4", aisle: "Produce", checked: false },
  { id: "wholewheat", label: "Whole wheat wraps or rotis", quantity: "1 pack", aisle: "Bakery", checked: false },
];
